export { default as themeReducer } from './theme-slice'
export { setLightTheme, setDarkTheme } from './theme-slice'
export { default as copyReducer } from './copy-slice'
export { setEmailCopied, setTelegramCopied } from './copy-slice'
export { default as langReducer } from './lang-slice'
export { setLanguage } from './lang-slice'
